# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/grapfruit/Documents/Another_Documents/Test1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/grapfruit/Documents/Another_Documents/Test1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grapfruit/Documents/Another_Documents/Test1/CMakeFiles /home/grapfruit/Documents/Another_Documents/Test1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/grapfruit/Documents/Another_Documents/Test1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MCalc

# Build rule for target.
MCalc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MCalc
.PHONY : MCalc

# fast build rule for target.
MCalc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/build
.PHONY : MCalc/fast

#=============================================================================
# Target rules for targets named MCalc_autogen

# Build rule for target.
MCalc_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MCalc_autogen
.PHONY : MCalc_autogen

# fast build rule for target.
MCalc_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc_autogen.dir/build.make CMakeFiles/MCalc_autogen.dir/build
.PHONY : MCalc_autogen/fast

MCalc_autogen/mocs_compilation.o: MCalc_autogen/mocs_compilation.cpp.o
.PHONY : MCalc_autogen/mocs_compilation.o

# target to build an object file
MCalc_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/MCalc_autogen/mocs_compilation.cpp.o
.PHONY : MCalc_autogen/mocs_compilation.cpp.o

MCalc_autogen/mocs_compilation.i: MCalc_autogen/mocs_compilation.cpp.i
.PHONY : MCalc_autogen/mocs_compilation.i

# target to preprocess a source file
MCalc_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/MCalc_autogen/mocs_compilation.cpp.i
.PHONY : MCalc_autogen/mocs_compilation.cpp.i

MCalc_autogen/mocs_compilation.s: MCalc_autogen/mocs_compilation.cpp.s
.PHONY : MCalc_autogen/mocs_compilation.s

# target to generate assembly for a file
MCalc_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/MCalc_autogen/mocs_compilation.cpp.s
.PHONY : MCalc_autogen/mocs_compilation.cpp.s

calc.o: calc.cpp.o
.PHONY : calc.o

# target to build an object file
calc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/calc.cpp.o
.PHONY : calc.cpp.o

calc.i: calc.cpp.i
.PHONY : calc.i

# target to preprocess a source file
calc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/calc.cpp.i
.PHONY : calc.cpp.i

calc.s: calc.cpp.s
.PHONY : calc.s

# target to generate assembly for a file
calc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/calc.cpp.s
.PHONY : calc.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MCalc.dir/build.make CMakeFiles/MCalc.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MCalc_autogen"
	@echo "... MCalc"
	@echo "... MCalc_autogen/mocs_compilation.o"
	@echo "... MCalc_autogen/mocs_compilation.i"
	@echo "... MCalc_autogen/mocs_compilation.s"
	@echo "... calc.o"
	@echo "... calc.i"
	@echo "... calc.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

